[tool.pdm]

[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Ariane Junkes", email = "ariane@gmail.com"},
]
dependencies = [
    "django>=4.1.7",
]
requires-python = ">=3.10"
license = {text = "MIT"}
